AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ts-template

  A template for a TypeScript Lambda function with SAM.

Parameters:
  Stage:
    Type: String
    Default: homologation
    Description: The stage name to deploy the API Gateway to.
    AllowedValues:
      - homologation
      - production

Globals:
  Function:
    Timeout: 30

Resources:
  ApiGatewayEndpoint:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: template-api
      StageName:
        Ref: Stage
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world
      Handler: src/application/handlers/hello-world.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HTTP:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayEndpoint
            Path: /hello
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/application/handlers/hello-world.ts
