AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ts-template

  A template for a TypeScript Lambda function with SAM.

Globals:
  Function:
    Timeout: 30
    LoggingConfig:
      LogFormat: JSON

Parameters:
  Stage:
    Type: String
    Description: If is homologation or production

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors: "'*'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/application/handlers/hello-world.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /hello
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/application/handlers/hello-world.ts

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Hello World function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/{Stage}/hello'
